[package]
name = "wiremock-grpc-protogen"
version = "0.1.0"
edition = "2021"
description = "Proto generated client-server code"
publish = false

[lib]
doc = false

[dependencies]
tonic = "0.8.2"
tonic-build = "0.8.2"
prost = "0.11.0"
